### ISSUE TITLE
申请添加我们的textharmony模型，Harmonizing Visual Text Comprehension and Generation 统一的视觉文本理解和生成，被NeurIPS 2024接收

### ISSUE THREAD

**Issue by JohnTang93** [shxie2020/Awesome-UGVFM#1]
git: https://github.com/bytedance/TextHarmony

paper: https://arxiv.org/abs/2407.16364

**Comment by shxie2020** [comment]
Great work! We have added it to the ar&diffusion column. Thanks again for the sharing.
